elements = {'enums': {},
 'fnmacros': {'MACRO_TEST': ('typeof({})*2', [0])},
 'functions': {'get_mem_from_pool': Type(Type('mem_header_t', '*'), (('nquantas', Type('ulong'), None),)),
               'memmgr_alloc': Type(Type('void', '*'), (('nbytes', Type('ulong'), None),)),
               'memmgr_alloc2': Type(Type('void', '*', '*'), (('nbytes', Type('ulong'), None),)),
               'memmgr_free': Type(Type('void'), (('ap', Type('void', '*'), None),)),
               'memmgr_init': Type(Type('void'), ())},
 'macros': {'VALUE_1': '15'},
 'structs': {'anon_struct0': Struct(('next', Type('union mem_header_union', '*'), None), ('size', Type('ulong'), None)),
             'anon_struct1': Struct(('next', Type('union mem_header_union', '*'), None), ('size', Type('ulong'), None))},
 'types': {'Align': Type('ulong'),
           'mem_header_t': Type('union mem_header_union'),
           'struct anon_struct0': Type('struct', 'anon_struct0'),
           'struct anon_struct1': Type('struct', 'anon_struct1'),
           'union mem_header_union': Type('union', 'mem_header_union')},
 'unions': {'mem_header_union': Union(('s', Type('struct anon_struct1'), None), ('align_dummy', Type('Align'), None))},
 'values': {'VALUE_1': 15,
            'base': None,
            'freep': 0,
            'pool': [0],
            'pool_free_pos': 0,
            'varTest': None,
            'varTest2': 10},
 'variables': {'base': (None, Type('mem_header_t')),
               'freep': (0, Type('mem_header_t', '*')),
               'pool': ([0], Type('byte', [None])),
               'pool_free_pos': (0, Type('ulong')),
               'varTest': (None, Type('int')),
               'varTest2': (10, Type('int'))}}
